# Generated by Django 5.2.5 on 2025-09-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrito",
            old_name="usuario_id",
            new_name="usuario",
        ),
        migrations.RenameField(
            model_name="carritoitem",
            old_name="carrito_id",
            new_name="carrito",
        ),
        migrations.RenameField(
            model_name="carritoitem",
            old_name="item_id",
            new_name="item",
        ),
    ]
