# Generated by Django 5.2.5 on 2025-09-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_usuario_id_carrito_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrito",
            old_name="usuario",
            new_name="usuario_id",
        ),
        migrations.RenameField(
            model_name="carritoitem",
            old_name="carrito",
            new_name="carrito_id",
        ),
        migrations.RenameField(
            model_name="carritoitem",
            old_name="item",
            new_name="item_id",
        ),
    ]
