# Generated by Django 5.2.5 on 2025-09-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_carrito_usuario_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carritoitem",
            old_name="carrito_id",
            new_name="carrito",
        ),
        migrations.RenameField(
            model_name="carritoitem",
            old_name="item_id",
            new_name="item",
        ),
    ]
