# Generated by Django 5.2.5 on 2025-09-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_rename_carrito_id_carritoitem_carrito_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrito",
            old_name="usuario_id",
            new_name="usuario",
        ),
    ]
