# Generated by Django 5.2.5 on 2025-09-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariofinal',
            name='es_proveedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariovendedor',
            name='es_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
