# Generated by Django 5.2.5 on 2025-09-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuariofinal_es_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofinal',
            name='es_proveedor',
        ),
        migrations.RemoveField(
            model_name='usuariovendedor',
            name='es_proveedor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='es_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
