# Generated by Django 5.2.4 on 2025-09-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='usuario_final',
            new_name='usuario',
        ),
    ]
