# Generated by Django 5.2.4 on 2025-09-03 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('user', '0002_usuariofinal_es_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='usuario_final',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.usuariofinal'),
        ),
    ]
