# Generated by Django 5.2.4 on 2025-09-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_usuario_final'),
        ('user', '0002_usuariofinal_es_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagenes',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='item',
            name='usuario_final',
        ),
        migrations.AddField(
            model_name='item',
            name='tiempo',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.usuariofinal'),
        ),
    ]
