# Generated by Django 5.2.4 on 2025-09-05 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_imagenes_item_imagen_and_more'),
        ('user', '0002_usuariofinal_es_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='usuario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.usuariovendedor'),
        ),
    ]
