# Generated by Django 5.2.4 on 2025-09-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_item_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tiempo',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
